# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    branches:
      only:
        - master

    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo

    working_directory: ~/repo

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - 'e5:f4:5c:00:12:6f:4a:a6:39:1f:70:aa:87:69:8e:1f'

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run build & tests!
      - run: yarn run build
      # - run: yarn test

      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              sudo apt install -y rsync
              rsync -av --delete -e "ssh -o StrictHostKeyChecking=no -p ${SSH_PORT}" --exclude='.cache' --exclude='.git' --exclude='.circleci' --exclude='.vscode' --exclude='.nyc_output' --exclude='coverage' ~/repo/ ${SSH_USER}@${SSH_HOST}:${SSH_PATH}
              ssh -o StrictHostKeyChecking=no -p ${SSH_PORT} ${SSH_USER}@${SSH_HOST} pm2 restart atom
            fi
